module beast.code.entity.codenamespace.user;

import beast.code.entity.toolkit;
import beast.code.entity.codenamespace.namespace;
import beast.util.identifiable;

/// Namespace whose symbols are generated from user (programmer) code - generated by an obtain function
final class UserNamespace : Namespace {
	mixin TaskGuard!("membersObtaining");

public:
	alias ObtainFunction = Symbol[]delegate();

public:
	this(Identifiable parent, ObtainFunction obtainFunction) {
		super(parent);

		obtainFunction_ = obtainFunction;
		taskManager.delayedIssueJob({ enforceDone_membersObtaining(); });
	}

public:
	override Symbol[] members() {
		enforceDone_membersObtaining();
		return super.members;
	}

	override Overloadset resolveIdentifier(Identifier id, DataEntity instance, MatchLevel matchLevel = MatchLevel.fullMatch) {
		enforceDone_membersObtaining();
		return super.resolveIdentifier(id, instance, matchLevel);
	}

private:
	final void execute_membersObtaining() {
		initialize_(obtainFunction_());
	}

private:
	ObtainFunction obtainFunction_;

}
