module beast.code.data.codenamespace.user;

import beast.code.toolkit;
import beast.code.data.codenamespace.namespace;

/// Namespace whose symbols are generated from user (programmer) code - generated by an obtain function
final class UserNamespace : Namespace {
	mixin TaskGuard!( "membersObtaining" );

public:
	alias ObtainFunction = Symbol[ ]delegate( );

public:
	this( Identifiable parent, ObtainFunction obtainFunction ) {
		super( parent );

		obtainFunction_ = obtainFunction;
		taskManager.issueJob( { enforceDone_membersObtaining( ); } );
	}

public:
	override Overloadset resolveIdentifier( Identifier id, DataEntity instance ) {
		enforceDone_membersObtaining( );
		return super.resolveIdentifier( id, instance );
	}

private:
	final void execute_membersObtaining( ) {
		initialize_( obtainFunction_( ) );
	}

private:
	ObtainFunction obtainFunction_;

}
