module beast.backend.interpreter.codeblock;

import beast.backend.interpreter.instruction;

/// Code block generated by the interpreter codebuilder (usually a code representing function)
final class InterpreterCodeBlock {

package:
	this(Instruction[] bytecode) {
		bytecode_ = bytecode;
	}

public:
	Instruction[] bytecode() {
		return bytecode_;
	}

private:
	Instruction[] bytecode_;

}
